library identifier: 'jenkins-pipeline-shared-library@master', 
        retriever: modernSCM([$class: 'GitSCMSource', remote: 'https://github.com/AmarPotki/jenkins-pipeline-shared-library.git'])

pipeline {
    agent any
    stages {
        stage('Audit tools') {                        
            steps {
                auditTools()
            }
        }
    }
}
